import { useCurrentFrame, useVideoConfig } from 'remotion';

const SubtitleOverlay = ({ subtitles, styleType }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const activeSubtitle = subtitles.find((subtitle) => {
    const startFrame = Math.floor(subtitle.start * fps);
    const endFrame = Math.floor(subtitle.end * fps);
    return frame >= startFrame && frame <= endFrame;
  });

  const styles = {
    hormozi: {
      position: 'absolute',
      left: '10%',
      right: '10%',
      bottom: '10%',
      textAlign: 'center',
      fontFamily: 'Impact, Arial, sans-serif',
      fontSize: '36px',
      fontWeight: '900',
      color: 'white',
      textTransform: 'uppercase',
      textShadow: '0 4px 6px rgba(0, 0, 0, 0.8)',
      padding: '15px 20px',
      backgroundColor: 'rgba(0, 0, 0, 0.9)',
      borderRadius: '12px',
      border: '4px solid #FFD700',
      zIndex: 10,
      opacity: activeSubtitle ? 1 : 0,
      transition: 'opacity 0.2s ease-in-out',
    },
    abdaal: {
      position: 'absolute',
      left: '10%',
      right: '10%',
      bottom: '10%',
      textAlign: 'center',
      fontFamily: 'Helvetica, Arial, sans-serif',
      fontSize: '28px',
      fontWeight: '600',
      color: '#F5F5F5',
      textShadow: '0 2px 4px rgba(0, 0, 0, 0.5)',
      padding: '10px 15px',
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      borderRadius: '10px',
      border: '2px solid #FFFFFF',
      zIndex: 10,
      opacity: activeSubtitle ? 1 : 0,
      transition: 'opacity 0.2s ease-in-out',
    },
    neonGlow: {
      position: 'absolute',
      left: '10%',
      right: '10%',
      bottom: '10%',
      textAlign: 'center',
      fontFamily: '"Orbitron", Arial, sans-serif',
      fontSize: '32px',
      fontWeight: '700',
      color: '#00FFDD',
      textShadow: '0 0 8px #00FFDD, 0 0 16px #00FFDD, 0 0 24px #FF00FF',
      padding: '12px 18px',
      background: 'linear-gradient(45deg, rgba(255, 0, 255, 0.2), rgba(0, 255, 221, 0.2))',
      borderRadius: '10px',
      border: '2px solid #FF00FF',
      zIndex: 10,
      opacity: activeSubtitle ? 1 : 0,
      transition: 'opacity 0.3s ease-in-out',
      animation: activeSubtitle ? 'neonFlicker 1.5s infinite alternate' : 'none',
    },
    retroWave: {
      position: 'absolute',
      left: '10%',
      right: '10%',
      bottom: '10%',
      textAlign: 'center',
      fontFamily: '"VCR OSD Mono", monospace',
      fontSize: '30px',
      fontWeight: '400',
      color: '#FF69B4',
      textShadow: '0 0 10px #FF1493, 0 0 20px #9400D3',
      padding: '10px 15px',
      background: 'rgba(0, 0, 0, 0.7)',
      borderRadius: '8px',
      border: '3px double #00FFFF',
      zIndex: 10,
      opacity: activeSubtitle ? 1 : 0,
      transition: 'opacity 0.2s ease-in-out',
      filter: 'contrast(1.2)',
      letterSpacing: '2px',
    },
    minimalPop: {
      position: 'absolute',
      left: '10%',
      right: '10%',
      bottom: '10%',
      textAlign: 'center',
      fontFamily: '"Poppins", Arial, sans-serif',
      fontSize: '28px',
      fontWeight: '500',
      color: '#FFFFFF',
      textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
      padding: '8px 12px',
      background: 'linear-gradient(135deg, #FF6B6B 0%, #FFE66D 100%)',
      borderRadius: '12px',
      border: 'none',
      zIndex: 10,
      opacity: activeSubtitle ? 1 : 0,
      transition: 'opacity 0.3s ease-in-out, transform 0.2s ease-in-out',
      transform: activeSubtitle ? 'scale(1)' : 'scale(0.95)',
    },
    none: {
      position: 'absolute',
      left: '10%',
      right: '10%',
      bottom: '10%',
      textAlign: 'center',
      fontFamily: 'Arial, sans-serif',
      fontSize: '24px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '0 2px 4px rgba(0, 0, 0, 0.8)',
      padding: '10px',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      borderRadius: '8px',
      zIndex: 10,
      opacity: activeSubtitle ? 1 : 0,
      transition: 'opacity 0.2s ease-in-out',
    },
  };

  return <div style={styles[styleType] || styles.none}>{activeSubtitle?.text || ''}</div>;
};

export default SubtitleOverlay;