name: Render Remotion Video

on:
  repository_dispatch:
    types: [render-video]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Construct Supabase URLs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          VIDEO_PATHS='${{ toJson(github.event.client_payload.videoUrls) }}'
          echo "Video paths: $VIDEO_PATHS"
          VIDEO_URLS_JSON=$(echo $VIDEO_PATHS | jq -c '[.[] | "https://fmkjdrdiifebucfpkbsz.supabase.co/storage/v1/object/public/avatars/\(.)"]')
          echo "VIDEO_URLS=$VIDEO_URLS_JSON" >> $GITHUB_ENV
          if [ -n "${{ github.event.client_payload.audioPath }}" ]; then
            AUDIO_URL="https://fmkjdrdiifebucfpkbsz.supabase.co/storage/v1/object/public/avatars/${{ github.event.client_payload.audioPath }}"
            echo "AUDIO_URL=$AUDIO_URL" >> $GITHUB_ENV
          else
            echo "AUDIO_URL=" >> $GITHUB_ENV
          fi

      - name: Render Video with Remotion
        env:
          SUBTITLES: ${{ toJson(github.event.client_payload.subtitles) }}
          STYLE_TYPE: ${{ github.event.client_payload.styleType }}
          OUTPUT_FILE: ${{ github.event.client_payload.outputFile }}
          VIDEO_URLS: ${{ env.VIDEO_URLS }}
          AUDIO_URL: ${{ env.AUDIO_URL }}
          DURATION: ${{ github.event.client_payload.duration }}
        run: |
          echo "Rendering video with props:"
          echo "Subtitles: $SUBTITLES"
          echo "Style Type: $STYLE_TYPE"
          echo "Video URLs: $VIDEO_URLS"
          echo "Audio URL: $AUDIO_URL"
          echo "Duration: $DURATION"
          echo "Output File: $OUTPUT_FILE"
          npx remotion render VideoWithSubtitlesAndAudio \
            --props "{\"videoUrls\": $VIDEO_URLS, \"audioUrl\": \"$AUDIO_URL\", \"subtitles\": $SUBTITLES, \"styleType\": \"$STYLE_TYPE\", \"duration\": $DURATION}" \
            --output="$OUTPUT_FILE.mp4"
        

      - name: Upload Rendered Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: "*.mp4"
          retention-days: 7
