name: Render Remotion Video

on:
  repository_dispatch:
    types: [render-video]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Render Video with Remotion
        env:
          VIDEO_URLS: ${{ toJson(github.event.client_payload.videoUrls) }}
          AUDIO_URL: ${{ github.event.client_payload.audioUrl }}
          DURATION: ${{ github.event.client_payload.duration }}
          TOTAL_DURATION_IN_FRAMES: ${{ github.event.client_payload.totalDurationInFrames }}
          AUDIO_VOLUME: ${{ github.event.client_payload.audioVolume }}
          OUTPUT_FILE: ${{ github.event.client_payload.outputFile }}
        run: |
          echo "Rendering video with props:"
          echo "Video URLs: $VIDEO_URLS"
          echo "Audio URL: $AUDIO_URL"
          echo "Duration: $DURATION"
          echo "Total Duration in Frames: $TOTAL_DURATION_IN_FRAMES"
          echo "Audio Volume: $AUDIO_VOLUME"
          echo "Output File: $OUTPUT_FILE"
          npx remotion render VideoWithAudio \
            --props "{\"videoUrls\": $VIDEO_URLS, \"audioUrl\": \"$AUDIO_URL\", \"totalDurationInFrames\": $TOTAL_DURATION_IN_FRAMES, \"audioVolume\": $AUDIO_VOLUME}" \
            --output="$OUTPUT_FILE.mp4"
          
      - name: Upload Rendered Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: "*.mp4"
          retention-days: 7
